spring:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 여부 설정
      path: /h2-console  # H2 콘솔 경로 설정
  datasource:
    driver-class-name: org.h2.Driver  # DB Driver 클래스명 설정
    url: jdbc:h2:~/test2  # DB 연결 URL 설정
    username: sa  # DB username
    password: # DB password

  jpa:
    hibernate:
      ddl-auto: create # Hibernate DDL 생성 전략 설정 (create, create-drop, update, validate, none)
    properties:
      dialect: org.hibernate.dialect.H2Dialect # Hibernate DB 방언 설정
      hibernate:
        show_sql: true # SQL 쿼리 출력 여부 설정
        format_sql: true # SQL 쿼리 포맷팅 여부 설정
        use_sql_comments: true # SQL 쿼리 주석 사용 여부 설정


